#! /usr/bin/env python

# Make external libs work with gevent, but still enable real threading
from gevent import monkey  # isort:skip

monkey.patch_all(thread=False)  # noqa: E702 isort:skip
# Make postgresql usable with gevent
import psycogreen.gevent  # isort:skip

psycogreen.gevent.patch_psycopg()  # noqa: E702 isort:skip

import re
import sys

from pytest import main

if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw?|\.exe)?$", "", sys.argv[0])
    sys.exit(main())
