[relay]
update_indexed_networks_interval = 120

[relay.gas_price_computation]
method = "rpc"
gas_price = 0

[trustline_index]
full_sync_interval = 300

[node_rpc]
host = "tlbc"
port = 8545
ssl = false

[account]
keystore_path = "keystore.json"
keystore_password_path = "keystore-password.txt"

# Configure logging
[logging.root]
level = "INFO"

[logging.loggers."api.resources"]
level = "DEBUG"

[logging.loggers.node]
level = "DEBUG"
