version: "3"
services:
  db:
    image: postgres
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

  parity:
    image: parity/parity:v1.10.6
    command: "--no-warp --auto-update none --no-download --chain kovan --jsonrpc-interface 0.0.0.0 --jsonrpc-hosts all -d /chaindata"
    volumes:
      - blockchain-data:/chaindata
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    expose:
      - "8545"
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    networks:
      - backend
    restart: unless-stopped

  relay:
    image: trustlines/relay
    depends_on:
      - "db"
      - "parity"
    volumes:
      - ./config.json:/opt/relay/config.json
      - ./addresses.json:/opt/relay/addresses.json
    # make relay server listen on port 5000. In a real scenario you will want to
    # put a proxy like nginx, apache or traefik in front of the relay server
    ports:
      - "5000:5000"
    environment:
      - PGHOST
      - PGUSER
      - PGDATABASE
      - PGPASSWORD
    networks:
      - backend
    restart: unless-stopped

  index:
    image: trustlines/py-eth-index
    depends_on:
      - "db"
      - "parity"
    environment:
      - PGHOST
      - PGUSER
      - PGDATABASE
      - PGPASSWORD
    networks:
      - backend
    restart: unless-stopped
    command: ["/opt/ethindex/bin/ethindex", "runsync", "--jsonrpc", "http://parity:8545"]
    volumes:
      - ./addresses.json:/tmp/addresses.json
      - ./contracts.json:/tmp/contracts.json


volumes:
  blockchain-data:
  postgres-data:
networks:
  backend:
